---
title: "Project 1"
author: "Zachary Muller"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Function
```{r}
ntickets = function(N, gamma, p){
  gamma = as.numeric(gamma)
  list <- qbinom(1-gamma, N:(N+N/10), p)
  ctr = 0

  for (x in list){
    if (x == N){
      nd = x + ctr
      break
    }
    ctr=ctr+1
  }
  mu = nd * p
  print(nd)
  sig = sqrt(mu*(1-p))

  plot(N:(N+N/10), 1 - pbinom(N, N:(N+N/10), p)-gamma, type = "o", pch = 19, col = "blue", xlab = "N", ylab = "ObjectiveDiscrete") # discrete plot
  abline(h=0, v=nd+1)


  list <- qnorm(1-gamma, seq(nd, nd+1, by=0.001)*p, sqrt(seq(nd, nd+1, by=0.001)*p*(1-p))) # Find N + 0.5 = qnorm
  # After finding, we know the approximation is n + num_sequences.
  ctr = 1
  tmp =1

  for(num in list){

    if (num > (N+0.5)){
      nc = (tmp * 0.001) + nd
      break
    }
    tmp = tmp+1
  }
  print(nc)
  plot(seq(N,floor(N+(N/10)), by=0.001),pnorm(seq(N,floor(N+(N/10)), by=0.001), floor((N+(N/10)+N)/2), sig) - gamma,type='S',col = "red", xlab = "n", ylab = "ObjectiveCont") # cont plot
  abline(v=nc, h=0, col='Blue')
  
  print(list("N":N, "nc":nc, "nd":nd, "gamma":gamma, "Pr"=p))
}
```


# Execution
```{r}
packagedeal::ntickets(400, 0.02, 0.95)
```
